[package]
name = "seamcarving"
version = "0.0.1"
authors = ["Ophir LOJKINE <ophir.lojkine@auto-grid.com>"]
edition = "2018"

[dependencies]
image = "0.21"
pathfinding = "1.1"
num-traits = "0.2"
quickcheck = "0.8"

[dev-dependencies]
quickcheck = "0.8"
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false